@baseUrl = http://localhost:3000
### Create a pizza
POST {{baseUrl}}/films
Content-Type: application/json

{
    "title":"Film",
    "duration":105,
    "budget":70,
    "link":""
}

### Read all pizzas
GET {{baseUrl}}/films

### Delete pizza identified by 2
DELETE {{baseUrl}}/films/2

### Update the pizza identified by 6
PATCH {{baseUrl}}/films/2
Content-Type: application/json

{
    "title":"Magic Green 2"
}